# Generated by Django 3.2.5 on 2021-08-04 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_auto_20210703_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='groupchat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_image/'),
        ),
        migrations.AlterField(
            model_name='members',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='messenger.groupchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messenger.groupchat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
